
insert into dogs (name, life_span, weight_min, weight_max, height_min, height_max, image_url) 
values 
('Bull Low', '10 - 12 years', 13, 15, 20, 25, 'http://localhost:3000/default-dog-image.png'),
('American Low', '12 - 15 years', 23, 25, 40, 50, 'http://localhost:3000/default-dog-image.png');

insert into temperaments (name)
values 
    ('Stubborn'),
    ('Adventurous'),
    ('Curious'),
    ('Playful'),
    ('Active'),
    ('Fun-loving'),
    ('Aloof'),
    ('Dignified'),
    ('Clownish'),
    ('Independent'),
    ('Happy'),
    ('Wild'),
    ('Hardworking'),
    ('Dutiful'),
    ('Outgoing'),
    ('Friendly'),
    ('Alert'),
    ('Confident'),
    ('Intelligent'),
    ('Courageous'),
    ('Loyal'),
    ('Brave'),
    ('Docile'),
    ('Responsive'),
    ('Composed'),
    ('Receptive'),
    ('Faithful'),
    ('Loving'),
    ('Protective'),
    ('Trainable'),
    ('Responsible'),
    ('Energetic'),
    ('Gentle'),
    ('Affectionate'),
    ('Devoted'),
    ('Assertive'),
    ('Dominant'),
    ('Strong Willed'),
    ('Obedient'),
    ('Reserved'),
    ('Kind'),
    ('Sweet-Tempered'),
    ('Tenacious'),
    ('Attentive'),
    ('Steady'),
    ('Bold'),
    ('Proud'),
    ('Reliable'),
    ('Fearless'),
    ('Lively'),
    ('Self-assured'),
    ('Cautious'),
    ('Eager'),
    ('Good-natured'),
    ('Spirited'),
    ('Companionable'),
    ('Even Tempered'),
    ('Rugged'),
    ('Fierce'),
    ('Refined'),
    ('Joyful'),
    ('Agile'),
    ('Amiable'),
    ('Excitable'),
    ('Determined'),
    ('Self-confidence'),
    ('Hardy'),
    ('Calm'),
    ('Good-tempered'),
    ('Watchful'),
    ('Hard-working'),
    ('Feisty'),
    ('Cheerful'),
    ('Sensitive'),
    ('Easygoing'),
    ('Adaptable'),
    ('Trusting'),
    ('Lovable'),
    ('Territorial'),
    ('Keen'),
    ('Familial'),
    ('Quick'),
    ('Bright'),
    ('Rational'),
    ('Powerful'),
    ('Gay'),
    ('Stable'),
    ('Quiet'),
    ('Inquisitive'),
    ('Strong'),
    ('Sociable'),
    ('Patient'),
    ('Suspicious'),
    ('Great-hearted'),
    ('Merry'),
    ('Tolerant'),
    ('Vocal'),
    ('Mischievous'),
    ('People-Oriented'),
    ('Bossy'),
    ('Cunning'),
    ('Athletic'),
    ('Boisterous'),
    ('Cooperative'),
    ('Trustworthy'),
    ('Self-important'),
    ('Respectful'),
    ('Thoughtful'),
    ('Generous'),
    ('Cat-like'),
    ('Sturdy'),
    ('Benevolent'),
    ('Clever'),
    ('Bubbly'),
    ('Opinionated'),
    ('Aggressive'),
    ('Extroverted'),
    ('Charming'),
    ('Unflappable'),
    ('Spunky'),
    ('Diligent'),
    ('Willful'),
    ('Fast'),
    ('Vigilant');

insert into dogs_and_temperaments (dog_id, temperament_id)
values
(1, 1),
(1, 3),
(2, 2),
(2, 3);

select * from dogs;
select * from temperaments;
select * from dogs_and_temperaments;

